### ISSUE TITLE
Change the libvirt image size from 128GB to 4GB

### ISSUE THREAD

**Issue by compromyse** [alvistack/vagrant-debian#2]
Libvirt has an option `machine_virtual_size` that 

> Sets the disk size in GB for the machine overriding the default specified in the box. Allows boxes to defined with a minimal size disk by default and to be grown to a larger size at creation time. Will ignore sizes smaller than the size specified by the box metadata. Note that currently there is no support for automatically resizing the filesystem to take advantage of the larger disk.

This allows the user to configure the disk size as needed. It would be beneficial to keep the image size to the minimum and allow the user to configure it..

Thanks!

**Comment by hswong3i** [comment]
But we are already in thin provisioning, so the real .qcow2 image shouldn't consume too much disk space, e.g.
```
hswong3i@hswong3i-inspiron-14-5420:~/Documents/osc$ sudo ls -alh /var/lib/libvirt/images/
total 4.3G
drwx--x--x 2 root root    4.0K May 19 17:35 .
drwxr-xr-x 7 root root    4.0K May 19 14:18 ..
-rwxr--r-- 1 root libvirt 1.8G May 19 17:34 alvistack-VAGRANTSLASH-kubernetes-1.30_vagrant_box_image_20240518.1.2_box_0.img
-rw------- 1 root libvirt 2.5G May 19 20:13 developer01_default.img
-rwxr--r-- 1 root libvirt 193K May 19 17:34 developer01_default-vdb.qcow2
```

From the other point of view, if 128GB already generally enough for R&D or CI/CD as vagrant box, what is the benefit to set the default disk size as 4GB, but need to enlarge it on-the-fly?

P.S. we already did `virt-sysprep` and `virt-sparsify` before packaging into vagrant box, shouldn't that enough? See https://github.com/alvistack/vagrant-debian/blob/e74d524/packer/debian-12-libvirt/packer.json#L61-L76

**Comment by compromyse** [comment]
I see... Guess that's fair.. Thank you!
